name: Build-ImmortalWrt

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      WORKDIR: /mnt/immortalwrt
      REPO_URL: https://github.com/immortalwrt/immortalwrt
      REPO_NAME: immortalwrt
      SSH_ENABLE: false

    steps:
    - uses: actions/checkout@v4

    - name: Prepare build space
      run: |
        sudo mkdir -p $WORKDIR
        sudo chown $USER:$USER $WORKDIR
        df -h

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
        gettext git libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone Source
      working-directory: /mnt
      run: |
        git clone $REPO_URL $REPO_NAME
        cd $REPO_NAME
        df -h

    - name: (Optional) SSH Debug
      if: env.SSH_ENABLE == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Run first custom script
      run: |
        FILE1=$(ls -1 immortalwrt*.sh | sed -n '1p' || true)
        if [ -f "$FILE1" ]; then
          chmod +x "$FILE1"
          ./"$FILE1"
        fi

    - name: Put .config
      run: |
        if [ -f "immortalwrt.config" ]; then
          cp immortalwrt.config /mnt/immortalwrt/.config
        fi

    - name: Feeds
      working-directory: /mnt/immortalwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run second custom script
      run: |
        FILE2=$(ls -1 immortalwrt*.sh | sed -n '2p' || true)
        if [ -f "$FILE2" ]; then
          chmod +x "$FILE2"
          ./"$FILE2"
        fi

    - name: Compile
      working-directory: /mnt/immortalwrt
      run: |
        make defconfig
        make -j$(nproc) || make -j1 V=s

    - name: Package bin
      working-directory: /mnt/immortalwrt
      run: |
        cd bin
        zip -r ../immortalwrt_bin.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt_bin
        path: /mnt/immortalwrt/immortalwrt_bin.zip

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: /mnt/immortalwrt/immortalwrt_bin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
